### ISSUE TITLE
use real db

### ISSUE THREAD

**Issue by webcane** [webcane/readme-app#11]

**Comment by webcane** [comment]
switched to postgresql.

- local

config from `src/main/resources/application-db.yml`. 
```
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/radb
    username: postgres
    password: postgres
```

profile **db** should be active.
see zsrc/main/resources/application.yml`
```
spring:
  profiles:
    active: app,dev,db,management,oauth2,openapi
```
Postgres should be installed manually.  db **radb**
Also it is possible to use db from a docker image.


- docker-compose

see `docker-compose.yml`
```
services:
  db:
    image: postgres:13.1-alpine
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=readmeapp_db
      - PGDATA=/var/lib/postgresql/data/pgdata

  app:
    image: 'webcane/readme-app-spring:latest'
    container_name: spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/readmeapp_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - db
 ```
back-end depends on db
db **readmeapp_db**

- cluster

see `helm/values.yaml`
```
app:
  name: readme-app-api
  image:
    repository: webcane/readme-app-spring

  #Spring related configuration
  configuration:
    spring:
      datasource:
        username: postgres
        password: postgres
        platform: postgresql
        driver-class-name: org.postgresql.Driver
      jpa:
        showsql: true
        generateddl: true
        open-in-view: false
        hibernate:
          ddlAuto: create #update #validate
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

postgresql:
  enabled: true
  service:
    port: 5432
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: readmeapp_db
```
[Postgres helm chart configuration](https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml)
