### ISSUE TITLE
swagger

### ISSUE THREAD

**Issue by webcane** [webcane/readme-app#26]
switch from swagger v2. to v3.
see https://springdoc.org/, https://github.com/springdoc/springdoc-openapi-demos

TODO
- [x] upgrade
- [x] version from the pom
- [x] add security
- [x] findBy issue
- [x] actuator endpoints

**Comment by webcane** [comment]
# upgrade

`openapi` spring profile

```
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /swagger
```

maven dependency:
```
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.5.4</version>
        </dependency>
```

https://springdoc.org/#migrating-from-springfox
